# Generated by Django 4.1.3 on 2022-12-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='overall_score',
        ),
    ]
