# Generated by Django 4.1.3 on 2022-12-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_player_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
