# Generated by Django 4.1.3 on 2022-12-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_players_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='current_player',
            field=models.BooleanField(default=False),
        ),
    ]
