# Generated by Django 4.1.3 on 2022-12-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_players_current_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
