# Generated by Django 4.1.3 on 2022-12-10 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
